language: node_js
node_js: 
  - "stable"
services:
  - postgresql
env:
  - NODE_ENV=test
  - SECRET_KEY=jaachi_secret
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database store_manager;' -U postgres
  - psql -c "CREATE USER jaachimma WITH PASSWORD 'password';" -U postgres
script: npm run test
after_script: npm run coverage
